name: Update README daily

on:
  schedule:
    - cron: "0 22 * * *"   # 22:00 UTC = 2:00 AM Abu Dhabi time
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # allows push

      - name: Update README timestamp
        run: |
          # Abu Dhabi is UTC+4
          TIMESTAMP=$(date -u -d "+4 hours" '+%Y-%m-%d %H:%M:%S UTC+4')
          sed -i "s|<!--LAST_UPDATED-->|$TIMESTAMP|g" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Daily Update: $(date -u -d '+4 hours')"
          git push
